<div class="container">
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"> <?php echo $this->getPageTitle() ?></h3>
                </div>
                <div class="panel-body">

                    <form action="/post/<?php echo $this->view->post->id; ?>/update" method="post" accept-charset="utf-8">

                        <div class="form-group">
                            <label class="control-label">Title</label>
                            <input type="text" name="title" class="form-control" value="<?php echo $this->view->post->title; ?>">
                        </div>

                        <div class="form-group">
                            <label class="control-label">Content</label>
                            <textarea  name="content" rows="15" class="form-control">
                                <?php echo $this->view->post->content; ?>
                            </textarea>
                        </div>

                        <a href="/posts">
                            <button type="button" class="btn btn-default">
                                Cancela
                            </button>
                        </a>

                        <button type="submit" class="btn btn-primary">
                            <i class="glyphicon glyphicon-floppy-save" aria-hidden="true"></i> Save
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>